# Generated by Django 3.1.6 on 2021-06-22 06:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0003_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
