# Generated by Django 3.1.6 on 2021-06-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0004_auto_20200926_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
