# Generated by Django 3.1.6 on 2021-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0005_mechanic_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='skill',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rescuing/Turnin', 'Rescuing/Turnin'), ('Work Done', 'Work Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True),
        ),
    ]
