# Generated by Django 3.1.6 on 2021-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('bird', 'bird'), ('bats', 'bats')], max_length=50),
        ),
    ]
